Non Graded Challenge 3

In [2]:
import numpy as np

Problem 1

In [9]:
vec_1= np.array([17,22,19])
vec_1

array([[17, 22, 19]])

In [12]:
vec_1.T

array([[17],
       [22],
       [19]])

Problem 2

In [14]:
A = np.array([17,22,19])
B = np.array([10,20,11])
C = np.array([5,12,9])

In [15]:
#Penjumlahan
A + B + C

array([32, 54, 39])

Hasilnya adalah array([32, 54, 39])

In [16]:
#Pengurangan
B - C

array([5, 8, 2])

Hasilnya adalah array([5, 8, 2])

In [17]:
#Perkalian Dot Product
A @ C

520

Hasil perkalian Dot Product adalah 520

In [18]:
#Perkalian Biasa
A * C

array([ 85, 264, 171])

Hasilnya adalah array([ 85, 264, 171])

In [19]:
#Norm A
np.linalg.norm(A)

33.67491648096547

jaraknya adalah sebesar 33.67

In [20]:
#sudut antara vektor A dan vektor B
cos_theta = A @ B / (np.linalg.norm(A)* np.linalg.norm(B))
cos_theta


0.9759590023331435

In [21]:
rad = np.arccos(cos_theta)
rad

0.21971776576153962

In [22]:
degr = np.degrees(rad)
degr

12.588900662180242

Sudut antara vektor A dan vektor B adalah 12.58 derajat

Problem 3

In [28]:
u = np.array([2,5])
v = np.array([3,1])

y = np.array([u,v])
y

array([[2, 5],
       [3, 1]])

In [29]:
y.shape

(2, 2)