Non Gradded Challenge 8

In [1]:
import numpy as np

In [6]:
import sympy as sy

Simbolik

Persamaan 1

In [7]:
x=sy.Symbol('x')



In [9]:
y = 3*x**2 - 6*x + 3
y

3*x**2 - 6*x + 3

In [10]:
sy.integrate(y)

x**3 - 3*x**2 + 3*x

In [12]:
def integral_y (x):
    return x**3 - 3*x**2 + 3*x

integral_y(10) - integral_y(1)

729

Persamaan 2

In [14]:
y1 = 8*x**3 - x**2 + 5*x - 1
y1

8*x**3 - x**2 + 5*x - 1

In [15]:
sy.integrate(y1)


2*x**4 - x**3/3 + 5*x**2/2 - x

In [16]:
def integral_y (x):
    return 2*x**4 - (1/3)*x**3 + (5/2)*x**2 - 1*x

integral_y(100) - integral_y(75)

136536954.16666666

Numerik

Persamaan 1

In [18]:
from scipy import integrate

In [21]:
def f(x):
   return x**3 - 3*x**2 + 3*x


Z = integrate.quad(f,3,20)
print(Z)

(32593.249999999993, 3.6185776597363873e-10)


Hasilnya 32593,25 dan eror 3.6e-10

In [23]:
def f(x):
   return x**3 - 3*x**2 + 3*x

x = np.linspace(3,20)
y = f(x)

A = integrate.trapz(y,x)
A

32603.99271137026

In [24]:
x

array([ 3.        ,  3.34693878,  3.69387755,  4.04081633,  4.3877551 ,
        4.73469388,  5.08163265,  5.42857143,  5.7755102 ,  6.12244898,
        6.46938776,  6.81632653,  7.16326531,  7.51020408,  7.85714286,
        8.20408163,  8.55102041,  8.89795918,  9.24489796,  9.59183673,
        9.93877551, 10.28571429, 10.63265306, 10.97959184, 11.32653061,
       11.67346939, 12.02040816, 12.36734694, 12.71428571, 13.06122449,
       13.40816327, 13.75510204, 14.10204082, 14.44897959, 14.79591837,
       15.14285714, 15.48979592, 15.83673469, 16.18367347, 16.53061224,
       16.87755102, 17.2244898 , 17.57142857, 17.91836735, 18.26530612,
       18.6122449 , 18.95918367, 19.30612245, 19.65306122, 20.        ])

In [25]:
y

array([   9.        ,   13.9272242 ,   20.54940543,   29.11710257,
         39.88087447,   53.09127999,   68.99887802,   87.85422741,
        109.90788702,  135.41041573,  164.6123724 ,  197.76431589,
        235.11680507,  276.92039881,  323.42565598,  374.88313543,
        431.54339603,  493.65699666,  561.47449617,  635.24645343,
        715.22342731,  801.65597668,  894.79466039,  994.89003731,
       1102.19266632, 1216.95310627, 1339.42191604, 1469.84965448,
       1608.48688047, 1755.58415286, 1911.39203053, 2076.16107234,
       2250.14183716, 2433.58488385, 2626.74077128, 2829.86005831,
       3043.19330381, 3266.99106665, 3501.50390569, 3746.98237979,
       4003.67704783, 4271.83846867, 4551.71720117, 4843.5638042 ,
       5147.62883662, 5464.16285731, 5793.41642513, 6135.64009894,
       6491.08443761, 6860.        ])

Persamaan 2

In [27]:
def f2(x):
   return 8*x**3 - x**2 + 5*x - 1


P = integrate.quad(f2,8,25)
print(P)

(769405.8333333333, 8.542120714475724e-09)


Hasilnya 769505,83 dan eror 8.542e-9

In [29]:
def f2(x):
   return x**3 - 3*x**2 + 3*x

x = np.linspace(3,20)
y = f2(x)

K = integrate.trapz(y,x)
K

32603.99271137026

In [30]:
x

array([ 3.        ,  3.34693878,  3.69387755,  4.04081633,  4.3877551 ,
        4.73469388,  5.08163265,  5.42857143,  5.7755102 ,  6.12244898,
        6.46938776,  6.81632653,  7.16326531,  7.51020408,  7.85714286,
        8.20408163,  8.55102041,  8.89795918,  9.24489796,  9.59183673,
        9.93877551, 10.28571429, 10.63265306, 10.97959184, 11.32653061,
       11.67346939, 12.02040816, 12.36734694, 12.71428571, 13.06122449,
       13.40816327, 13.75510204, 14.10204082, 14.44897959, 14.79591837,
       15.14285714, 15.48979592, 15.83673469, 16.18367347, 16.53061224,
       16.87755102, 17.2244898 , 17.57142857, 17.91836735, 18.26530612,
       18.6122449 , 18.95918367, 19.30612245, 19.65306122, 20.        ])

In [31]:
y

array([   9.        ,   13.9272242 ,   20.54940543,   29.11710257,
         39.88087447,   53.09127999,   68.99887802,   87.85422741,
        109.90788702,  135.41041573,  164.6123724 ,  197.76431589,
        235.11680507,  276.92039881,  323.42565598,  374.88313543,
        431.54339603,  493.65699666,  561.47449617,  635.24645343,
        715.22342731,  801.65597668,  894.79466039,  994.89003731,
       1102.19266632, 1216.95310627, 1339.42191604, 1469.84965448,
       1608.48688047, 1755.58415286, 1911.39203053, 2076.16107234,
       2250.14183716, 2433.58488385, 2626.74077128, 2829.86005831,
       3043.19330381, 3266.99106665, 3501.50390569, 3746.98237979,
       4003.67704783, 4271.83846867, 4551.71720117, 4843.5638042 ,
       5147.62883662, 5464.16285731, 5793.41642513, 6135.64009894,
       6491.08443761, 6860.        ])