Latihan 4

Pandas


In [108]:
!pip install pandas

In [109]:
import pandas as pd

In [110]:
import numpy as np

Series

In [111]:
pd.Series([2,3,6]) #Sebelah kiri index sebelah kanan values

0    2
1    3
2    6
dtype: int64

In [112]:
pd.Series(['a','b','c'])

0    a
1    b
2    c
dtype: object

In [113]:
pd.Series(['a',3, 4.5,'c'])

0      a
1      3
2    4.5
3      c
dtype: object

In [114]:
#Kalo bisa object ditransformasi jadi integer

In [115]:
revenues = pd.Series ([5555,7000,1980])

In [116]:
revenues

0    5555
1    7000
2    1980
dtype: int64

In [117]:
revenues.index

RangeIndex(start=0, stop=3, step=1)

In [118]:
revenues.values

array([5555, 7000, 1980], dtype=int64)

In [119]:
pd.Series([2,7,5], 
index=['val_1','val_2', 'val _3'])

val_1     2
val_2     7
val _3    5
dtype: int64

In [120]:
city_revenues = pd.Series ([4200,8000,6500], 
                            index=['Amsterdam','Toronto','Tokyo'])

In [121]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [122]:
city_employee_count = pd.Series({"Amsterdam":5,"Tokyo":8})
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [123]:
city_employee_count.keys()

Index(['Amsterdam', 'Tokyo'], dtype='object')

In [124]:
city_employee_count.values

array([5, 8], dtype=int64)

In [125]:
"Tokyo" in city_employee_count

True

In [126]:
"Jakarta" in city_employee_count

False

In [127]:
city_employee_count = pd.Series({"Amsterdam":5,"Tokyo":8})
city_employee_count2 = pd.Series({"Jakarta":5,"Kyoto":8})
city_employee_count.append(city_employee_count2)

Amsterdam    5
Tokyo        8
Jakarta      5
Kyoto        8
dtype: int64

Dataframe

In [128]:
pd.DataFrame({"kolom_1":[1,2,3,4],
              "kolom_2":['a','b','c','d']})


kolom_1 kolom_2
0        1       a
1        2       b
2        3       c
3        4       d

In [129]:
city_data = pd.DataFrame({"revenue":city_revenues, "employee_count": city_employee_count})

In [130]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [131]:
city_data.loc["Amsterdam"]

revenue           4200.0
employee_count       5.0
Name: Amsterdam, dtype: float64

In [132]:
city_data.loc["Amsterdam":"Tokyo"]

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0

In [133]:
city_data.loc["Tokyo","revenue"]

6500

In [134]:
city_data.loc[["Amsterdam","Toronto"],"revenue"]

Amsterdam    4200
Toronto      8000
Name: revenue, dtype: int64

In [135]:
city_data.loc[["Amsterdam","Toronto"],:]

revenue  employee_count
Amsterdam     4200             5.0
Toronto       8000             NaN

In [136]:
city_revenues.sum()

18700

In [137]:
city_revenues.max()

8000

In [138]:
city_data.index

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [139]:
city_data.columns

Index(['revenue', 'employee_count'], dtype='object')

In [140]:
city_data.values

array([[4.2e+03, 5.0e+00],
       [6.5e+03, 8.0e+00],
       [8.0e+03,     nan]])

In [141]:
#axes
city_data.axes

[Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object'),
 Index(['revenue', 'employee_count'], dtype='object')]

In [142]:
city_data.axes[0]

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [143]:
city_data.axes[1]

Index(['revenue', 'employee_count'], dtype='object')

#Axis 0 = baris
#axis 1 = kolom

#.drop buat buang data (axis = 0/1)


In [144]:
city_data.keys()

Index(['revenue', 'employee_count'], dtype='object')

In [145]:
"amsterdam" in city_data

False

In [146]:
"revenue" in city_data

True

In [147]:
4200 in city_data

False

.loc dan .iloc

In [148]:
#.loc = label tertampil
#.iloc = index default
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [149]:
city_revenues["Toronto"]

8000

In [150]:
city_revenues[1]

8000

In [151]:
city_revenues[1:3]

Toronto    8000
Tokyo      6500
dtype: int64

In [152]:
city_revenues[:2]

Amsterdam    4200
Toronto      8000
dtype: int64

In [153]:
city_revenues[1:]

Toronto    8000
Tokyo      6500
dtype: int64

In [154]:
city_revenues[-1]

6500

In [155]:
city_revenues['Amsterdam':'Tokyo']

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [156]:
colors = pd.Series(['red', 'purple','blue','green','yellow'], index=[1,2,3,5,8])

In [157]:
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [158]:
colors.loc[1]


'red'

In [159]:
colors.iloc[1]

'purple'

In [160]:
colors.loc[1:3]

1       red
2    purple
3      blue
dtype: object

In [161]:
colors.iloc[1:3]

2    purple
3      blue
dtype: object

In [163]:
colors.iloc[-2]

'green'

Series 1 Dimensi

Data Frame 2 Dimensi

In [164]:
toys = pd.DataFrame([{"name":"ball","shape":"sphere"},"name:rubik"])

AttributeError: 'str' object has no attribute 'keys'

In [165]:
further_city_data = pd.DataFrame({"revenue":[7000,3400],"employee_count":[2,2]}, index=["New York","Barcelona"])

In [166]:
further_city_data

revenue  employee_count
New York      7000               2
Barcelona     3400               2

In [167]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [168]:
all_city_data = pd.concat([city_data,further_city_data],sort=False)
all_city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN
New York      7000             2.0
Barcelona     3400             2.0

In [169]:
all_city_data = pd.concat([city_data,further_city_data],sort=True)
all_city_data

employee_count  revenue
Amsterdam             5.0     4200
Tokyo                 8.0     6500
Toronto               NaN     8000
New York              2.0     7000
Barcelona             2.0     3400

axis = 0 Vertikal (default)

axis = 1 Horizontal

In [170]:
city_countries = pd.DataFrame({
    "country": ["Holland", "Japan", "Holland", "Canada", "Spain"],
    "capital": [1, 1, 0, 0, 0]},
    index=["Amsterdam", "Tokyo", "Rotterdam", "Toronto", "Barcelona"]
)

In [171]:
city_countries

country  capital
Amsterdam  Holland        1
Tokyo        Japan        1
Rotterdam  Holland        0
Toronto     Canada        0
Barcelona    Spain        0

In [172]:
pd.concat([all_city_data,city_countries],axis=1)

employee_count  revenue  country  capital
Amsterdam             5.0   4200.0  Holland      1.0
Tokyo                 8.0   6500.0    Japan      1.0
Toronto               NaN   8000.0   Canada      0.0
New York              2.0   7000.0      NaN      NaN
Barcelona             2.0   3400.0    Spain      0.0
Rotterdam             NaN      NaN  Holland      0.0

In [173]:
pd.concat([all_city_data,city_countries],axis=1, join='inner')

employee_count  revenue  country  capital
Amsterdam             5.0     4200  Holland        1
Tokyo                 8.0     6500    Japan        1
Toronto               NaN     8000   Canada        0
Barcelona             2.0     3400    Spain        0

In [174]:
pd.concat([all_city_data,city_countries],axis=1, join='outer')

employee_count  revenue  country  capital
Amsterdam             5.0   4200.0  Holland      1.0
Tokyo                 8.0   6500.0    Japan      1.0
Toronto               NaN   8000.0   Canada      0.0
New York              2.0   7000.0      NaN      NaN
Barcelona             2.0   3400.0    Spain      0.0
Rotterdam             NaN      NaN  Holland      0.0

In [175]:
city_countries

country  capital
Amsterdam  Holland        1
Tokyo        Japan        1
Rotterdam  Holland        0
Toronto     Canada        0
Barcelona    Spain        0

In [176]:
cities = pd.concat([all_city_data, city_countries], axis=1, sort=False)
cities

employee_count  revenue  country  capital
Amsterdam             5.0   4200.0  Holland      1.0
Tokyo                 8.0   6500.0    Japan      1.0
Toronto               NaN   8000.0   Canada      0.0
New York              2.0   7000.0      NaN      NaN
Barcelona             2.0   3400.0    Spain      0.0
Rotterdam             NaN      NaN  Holland      0.0

In [177]:
#.merge menambahkan hanya bisa secara horizontal

In [178]:
countries = pd.DataFrame({
    "population_millions": [17, 127, 37],
    "continent": ["Europe", "Asia", "North America"]
}, index=["Holland", "Japan", "Canada"])
countries

population_millions      continent
Holland                   17         Europe
Japan                    127           Asia
Canada                    37  North America

In [183]:
pd.merge(cities,countries,left_on="country",right_index=True)#Hanya yang bersinggungan dua-duanya

employee_count  revenue  country  capital  population_millions  \
Amsterdam             5.0   4200.0  Holland      1.0                   17   
Rotterdam             NaN      NaN  Holland      0.0                   17   
Tokyo                 8.0   6500.0    Japan      1.0                  127   
Toronto               NaN   8000.0   Canada      0.0                   37   

               continent  
Amsterdam         Europe  
Rotterdam         Europe  
Tokyo               Asia  
Toronto    North America

In [180]:
pd.merge(cities,countries,left_on="country",right_index=True, how="left") #Left ambil yang sebelah kiri (city)

employee_count  revenue  country  capital  population_millions  \
Amsterdam             5.0   4200.0  Holland      1.0                 17.0   
Tokyo                 8.0   6500.0    Japan      1.0                127.0   
Toronto               NaN   8000.0   Canada      0.0                 37.0   
New York              2.0   7000.0      NaN      NaN                  NaN   
Barcelona             2.0   3400.0    Spain      0.0                  NaN   
Rotterdam             NaN      NaN  Holland      0.0                 17.0   

               continent  
Amsterdam         Europe  
Tokyo               Asia  
Toronto    North America  
New York             NaN  
Barcelona            NaN  
Rotterdam         Europe

NBA Analysis

In [184]:
df = pd.read_csv('https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/nbaallelo.csv')