Latihan Hari ke 3 

16 Maret 2022

Function

In [ ]:
#def function_name(parameters)
#docstring(sama kaya comment)
'''docstring'''

In [13]:
def printme(str_input):
    print(str_input)

printme("Hello")
printme("World")
printme(str_input="Hello World")
#printme fungsi yang dibikin sendiri
#rint fungsi bawaan dari python

Hello
World
Hello World


In [5]:
def my_function(p,l):
 print(p*l)
my_function(10,10)

100


In [10]:
def changeme(mylist):
    mylist = mylist+[1,2,3,4]
    print('\nValues inside the function:', mylist)
    return mylist

mylist = [10,20,30]
print("\nValues outside the function - before:", mylist)
mylist = changeme(mylist)
print("\nValues outside the function - after:", mylist)


Values outside the function - before: [10, 20, 30]

Values inside the function: [10, 20, 30, 1, 2, 3, 4]

Values outside the function - after: [10, 20, 30, 1, 2, 3, 4]


In [12]:
def changeme(mylist):
    mylist = mylist+[1,2,3,4]
    print('\nValues inside the function:', mylist)
    

mylist = [10,20,30]
changeme(mylist)
print("\nValues outside the function", mylist)


Values inside the function: [10, 20, 30, 1, 2, 3, 4]

Values outside the function [10, 20, 30]


In [18]:
def printinfo( name, age ):
    print("Name : ", name)
    print("Age. : ", age)
printinfo(age=4, name="a")


Name :  a
Age. :  4


In [22]:
def printinfo( name, age = 26 ):
   '''This prints a passed info into this function'''
   print("Name : ", name)
   print("Age  : ", age)
   print("")

# Now you can call printinfo function
printinfo( age=50, name="hacktiv8" )
printinfo( name="hacktiv" )

Name :  hacktiv8
Age  :  50

Name :  hacktiv
Age  :  26



In [20]:
def printinfo( name, age = 26 ):
   '''This prints a passed info into this function'''
   print("Name : ", name)
   print("Age  : ", age)
   print("")

# Now you can call printinfo function
printinfo( age=50, name="hacktiv8" )

Name :  hacktiv8
Age  :  50



In [25]:
def printinfo( arg1, *vartuple ):
# def printinfo(arg1, arg2, arg3, arg4):
   '''This prints a variable passed arguments'''
   print('arg1     : ', arg1)
   print('vartuple : ', vartuple)
   print('')
   
   for var in vartuple:
      print('isi vartuple : ', var) 

# Now you can call printinfo function
printinfo( 10 )
printinfo( 70, 60, 50, "a" )

arg1     :  10
vartuple :  ()

arg1     :  70
vartuple :  (60, 50, 'a')

isi vartuple :  60
isi vartuple :  50
isi vartuple :  a


In [26]:
def person_car(total_data, **kwargs):
  '''Create a function to print who owns what car'''
  print('Total Data : ', total_data)
  for key, value in kwargs.items():
    print('Person : ', key)
    print('Car    : ', value)
    print('')

person_car(3, jimmy='chevrolet', frank='ford', tina='honda')
person_car(3)

# Parameters (jimmy='chevrolet', frank='ford', tina='honda') will be equal to
# kwargs = {
#     'jimmy': 'chevrolet',
#     'frank': 'ford',
#     'tina': 'honda'
# }

Total Data :  3
Person :  jimmy
Car    :  chevrolet

Person :  frank
Car    :  ford

Person :  tina
Car    :  honda

Total Data :  3


In [27]:
# Function definition is here
sum = lambda arg1, arg2: arg1 + arg2

# That lambda function will be equal to :
# def sum(arg1, arg2):
#     return arg1+arg2

# Now you can call sum as a function
print("Value of total : ", sum( 10, 20 ))
print("Value of total : ", sum( 20, 20 ))

Value of total :  30
Value of total :  40


In [28]:
# Function definition is here
def sum(arg1, arg2):
    # Add both the parameters and return them."
    total = arg1 + arg2
    return total

# Now you can call sum function
total = sum(10, 20)
print("Result function : ", total)

Result function :  30


In [1]:
# Function definition is here
sum = lambda arg1, arg2: arg1 + arg2

# That lambda function will be equal to :
# def sum(arg1, arg2):
#     return arg1+arg2

# Now you can call sum as a function
print("Value of total : ", sum( 10, 20 ))
print("Value of total : ", sum( 20, 20 ))

Value of total :  30
Value of total :  40


In [1]:
# Function definition is here
def sum(arg1, arg2):
    # Add both the parameters and return them."
    total = arg1 + arg2
    return total

# Now you can call sum function
total = sum(10, 20)
print("Result function : ", total)

Result function :  30


In [2]:
# Declare a global variable
total = 0

# Create sum function
def sum( arg1, arg2 ):
   total = arg1 + arg2; 
   print("Inside the function local total   : ", total)

# Call a function
sum( 10, 20 )
print("Outside the function global total : ", total)

Inside the function local total   :  30
Outside the function global total :  0


In [3]:
# Declare a global variable
total = 0

# Create sum function
def sum( arg1, arg2 ):
   total = arg1 + arg2; 
   print("Inside the function local total   : ", total)
   return total

# Call a function
print("Outside the function global total - before : ", total)
total = sum( 10, 20 )
print("Outside the function global total - after  : ", total)

Outside the function global total - before :  0
Inside the function local total   :  30
Outside the function global total - after  :  30


In [5]:
# Example of docstring in a function

def sum_number(num1, num2):
  '''
  This function is used to sum of 2 variables.
  :param num1: Input number 1 | int or float
  :param num2: Input number 2 | int or float
  
  :return: num3: Sum of number | int or float
  '''

  num3 = num1 + num2
  return num3
  
print(sum_number.__doc__)


  This function is used to sum of 2 variables.
  :param num1: Input number 1 | int or float
  :param num2: Input number 2 | int or float
  
  :return: num3: Sum of number | int or float
  


Module and Package

In [6]:
import person
print(person.name)

zack


In [7]:
import sys
print(sys.path)

['c:\\Users\\Muhamad Afif\\Documents\\Hacktiv8\\learning_journal\\Fase 0', 'C:\\Users\\Muhamad Afif\\anaconda3\\python39.zip', 'C:\\Users\\Muhamad Afif\\anaconda3\\DLLs', 'C:\\Users\\Muhamad Afif\\anaconda3\\lib', 'C:\\Users\\Muhamad Afif\\anaconda3', '', 'C:\\Users\\Muhamad Afif\\anaconda3\\lib\\site-packages', 'C:\\Users\\Muhamad Afif\\anaconda3\\lib\\site-packages\\locket-0.2.1-py3.9.egg', 'C:\\Users\\Muhamad Afif\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\Muhamad Afif\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Muhamad Afif\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\Muhamad Afif\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Muhamad Afif\\.ipython', 'C:\\Users\\Muhamad Afif\\AppData\\Roaming\\Python\\Python39\\site-packages']


In [8]:
import person
print(person.devices)

['laptop', 'smartphone', 'tablet']


In [9]:
import person
print(person.display)

<function display at 0x000001A541CB74C0>


Numpy

In [7]:
!pip install numpy

In [2]:
import numpy as np

In [29]:
tinggi = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
berat = [60.5, 61.5, 62.5, 63.5, 64.5, 65.7]

np_tinggi= np.array(tinggi)
np_berat = np.array(berat)

np_berat/np_tinggi

array([35.58823529, 34.16666667, 32.89473684, 57.72727273, 58.10810811,
       58.66071429])

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
print(np.arange(3,10,2))

[3 5 7 9]


In [34]:
arr = np.array([1,2,3,4])
arr_new = np.append(arr, [7,8,9])
arr_new

array([1, 2, 3, 4, 7, 8, 9])

In [35]:
np.delete(arr_new,3)

array([1, 2, 3, 7, 8, 9])

In [36]:
#0-D/Skalar
arr= np.array(6)
print(arr)

6


In [37]:
#Mengecek berapa dimensi
arr.ndim

0

In [38]:
arr.shape

()

In [40]:
#1-D/Vektor
arr=np.array([1,2,3,4])
print(arr)



[1 2 3 4]


In [41]:
arr.ndim

1

In [42]:
arr.shape

(4,)

In [45]:
#2-D/matrix
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)


[[1 2 3 4]
 [5 6 7 8]]


In [47]:
arr.ndim

2

In [48]:
arr.shape #Jumlah Baris dan Kolom

(2, 4)

In [49]:
#Latihan
arr = np.array([[[1,2,3,4], [5,6,7,8]]])
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]]


In [50]:
arr.ndim

3

In [51]:
arr.shape

(1, 2, 4)

In [52]:
arr.size #Menghitung jumlah elemen

8

In [53]:
arr = np.arange(6)
print(arr)


[0 1 2 3 4 5]


In [54]:
matriks = arr.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [55]:
arr = np.arange(9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [57]:
matriks = arr.reshape(3,3)
print(matriks)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [59]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [60]:
a.shape

(6,)

In [63]:
a2 = a[np.newaxis,:]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [62]:
a3 = a[:, np.newaxis]
print(a3.shape)
print(a3)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [66]:
a_e = np.expand_dims(a, axis=1)
print(a_e.shape)
print(a_e)


(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [69]:
a_e2 = np.expand_dims(a, axis=0)
print(a_e2.shape)
print(a_e2)

(1, 6)
[[1 2 3 4 5 6]]


In [71]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [73]:
a_e2= np.expand_dims(arr_2d, axis=2)
a_e2.shape

(2, 4, 1)

In [74]:
a_e2= np.expand_dims(arr_2d, axis=1)
a_e2.shape

(2, 1, 4)

In [76]:
#Soal
arr = np.array([1,2,7,4,10,5])
print(arr[2:6])

[ 7  4 10  5]


In [77]:
arr = np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])

[7 5]


In [78]:
arr = np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3]) #dari 0

[ 1  4 13]


In [79]:
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(arr[0,2]) #baris ke 0 kolom ke 2

3


In [81]:
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(arr[2,2:4]) #index ke 2 dari index kedua urutan ke 2 dan 3

[11 12]


In [83]:
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(arr[2:3,3]) #index ke 2 urutan ke 3

[12]


In [86]:
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(arr[1:3,3]) #index ke 1 dan 2urutan ke 3

[ 8 12]


In [87]:
print(arr[arr>=3]) #ngurutin nilai lebih besar sama dengan 3

[ 3  4  5  6  7  8  9 10 11 12]


In [92]:
a_1 = np.array(([1,1], 
               [2,2]))
a_2 = np.array(([1,1], 
               [2,2]))
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [1, 1],
       [2, 2]])

In [94]:
np.hstack((a_1,a_2))

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [96]:
arr_new = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
new_arr = arr_new.reshape(2,3,-1)#unknown dimension ( 2 baris,3 kolom, -1 unknown dimension)
print(new_arr.shape)
print(new_arr)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
